version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: richard-one
    address: cosmos1rcdwxwjptyftc0lxh62u3a3mzkn5vzj64k09lg
    coins: ["10000token", "1000stake"]
  - name: richard-two
    address: cosmos1jk6gmmppzeu5vyg5x3nyw8zty546fy4a5qv7pq
    coins: ["1000token", "1000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
